# Generated by Django 3.2 on 2023-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230419_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeekabooUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('total_rating', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
