# Generated by Django 3.2 on 2023-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_peekaboouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peekaboouser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='peekaboouser',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
